# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octoai < Formula
  desc "The CLI for the OctoAI Compute Service."
  homepage "https://octoai.cloud"
  version "0.4.0"
  license ":cannot_represent"

  depends_on "docker" => :optional
  depends_on "git"
  depends_on "python"

  on_macos do
    if Hardware::CPU.arm?
      url "https://s3.amazonaws.com/downloads.octoai.cloud/octoai/v0.4.0/octoai_0.4.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "af763fccafdfeb54a8df431bbc71890c16382160ecac708691f25502bf6a4b89"

      def install
        bin.install "octoai"
      end
    end
    if Hardware::CPU.intel?
      url "https://s3.amazonaws.com/downloads.octoai.cloud/octoai/v0.4.0/octoai_0.4.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0b4f5d3207b79878858cb62574b4285a6ff4cc93f2eed5d6a873d1c02fa2f023"

      def install
        bin.install "octoai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://s3.amazonaws.com/downloads.octoai.cloud/octoai/v0.4.0/octoai_0.4.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f2c2628c6689c34917a356a08a6c95d8674c533ff822bde5ec310ed5a003dd08"

      def install
        bin.install "octoai"
      end
    end
    if Hardware::CPU.intel?
      url "https://s3.amazonaws.com/downloads.octoai.cloud/octoai/v0.4.0/octoai_0.4.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "821cd941cf821d99162b47a02f5b28e45c4bb36673befbde4e0964e354ad6ef7"

      def install
        bin.install "octoai"
      end
    end
  end

  def caveats
    <<~EOS
      Docker is required for operation but not required by the formula.
    EOS
  end

  test do
    system "#{bin}/octoai --version"
  end
end
