# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octoai < Formula
  desc "The CLI for the OctoAI Compute Service."
  homepage "https://octoai.cloud"
  version "0.5.24"
  license ":cannot_represent"

  on_macos do
    if Hardware::CPU.intel?
      url "https://s3.amazonaws.com/downloads.octoai.cloud/octoai/v0.5.24/octoai_0.5.24_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "807a6fe2ed5c295becf46b224e282efb688e43df9a72a177b739a747804ef780"

      def install
        bin.install "octoai"
      end
    end
    if Hardware::CPU.arm?
      url "https://s3.amazonaws.com/downloads.octoai.cloud/octoai/v0.5.24/octoai_0.5.24_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "22ab3d31e6fe5446a18f3ab0e41f495d8be873108c5e076d3c5214154ca2406f"

      def install
        bin.install "octoai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://s3.amazonaws.com/downloads.octoai.cloud/octoai/v0.5.24/octoai_0.5.24_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "d07fbd265f62974a2156cbce42b038573173377955ea0a70ce9a3e5446543e68"

      def install
        bin.install "octoai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://s3.amazonaws.com/downloads.octoai.cloud/octoai/v0.5.24/octoai_0.5.24_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "76b3db79adbd3c9f94696ea15c4e9e00c77401f5afcbc9a414755fc82cff7e3c"

      def install
        bin.install "octoai"
      end
    end
  end

  def caveats
    <<~EOS
      Docker is required for operation but not required by the formula.
    EOS
  end

  test do
    system "#{bin}/octoai --version"
  end
end
